version: '3'

services:
  web-server:
    container_name: nginx_menu
    restart: always
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./docker/nginx/logs:/var/log/nginx
      - ./app:/var/www/html/app
    ports:
      - '80:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  php:
    build: ./docker/php
    container_name: php_menu
    restart: always
    volumes:
      - ./app:/var/www/html/app
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"