# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Validator\Infrastructure\ValidatorFactory:
        arguments:
            $pathToValidationLangDir: '%kernel.project_dir%/translations/validation/lang'
            $locale: 'ru'
        lazy: true
    App\Infrastructure\EventSubscribers\ExceptionEventSubscriber:

    App\Cli\CronJob\Hourly\MailRuWeatherParser:
        arguments:
            $mailRuWeatherUrl: '%env(MAIL_RU_WEATHER_URL)%'

    App\Cli\CronJob\Daily\MorningForecastTelegramNotifier:
        arguments:
            $telegramApiToken: '%env(TELEGRAM_BOT_API_TOKEN)%'
            $telegramChatId: '%env(TELEGRAM_CHAT_ID)%'
            $telegramApiUrl: '%env(TELEGRAM_API_URL)%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
