version: '3'

services:
  web-server:
    container_name: nginx_menu
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ../app:/var/www/html/app
    ports:
      - '80:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - menu-dev-net
  php:
    build:
      context: ./php
      args:
        - USER_ID=${USER_ID}
        - USER=${USER}
    container_name: php_menu
    restart: always
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - ../app:/var/www/html/app
      - ./php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/logs/php:/var/log/php
      - ./php/logs/app:/var/log/app
      - ./php/logs/xdebug:/var/log/xdebug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - menu-dev-net
  db:
    image: mysql
    container_name: mysql_menu
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - menu-dev-net
volumes:
  mysql_data:
networks:
  menu-dev-net:
    driver: bridge