version: '3'

services:
  web-server:
    container_name: nginx_menu
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./docker/nginx/logs:/var/log/nginx
      - ../app:/var/www/html/app
    ports:
      - '80:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - menu-dev-net
  php:
    build: php
    container_name: php_menu
    restart: always
    volumes:
      - ../app:/var/www/html/app
#      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - menu-dev-net
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - menu-dev-net
volumes:
  mysql_data:
networks:
  menu-dev-net:
    driver: bridge