twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/src/Shared/Infrastructure/templates'
    paths:
        '%kernel.project_dir%/src/Landing/Infrastructure/templates': 'landing'
when@test:
    twig:
        strict_variables: true
