twig:
    file_name_pattern: '*.twig'

#paths:
#    'email/default/templates': ~
#    'backend/templates': 'admin'

default_path: '%kernel.project_dir%/src/Shared/Infrastructure/templates'

when@test:
    twig:
        strict_variables: true
